help:
	@echo "====== Bem vindo ao sistema de criptografia RSA. ======"
	@echo "Para rodar qualquer comando: make <command> <arguments..>'."
	@echo "    "
	@echo "    help - imprime essa mensagem de ajuda"
	@echo "    "
	@echo "    run"
	@echo "        Roda o projeto apresentando o menu."
	@echo "    "
	@echo "    compile"
	@echo "        Compila todos os arquivos cpp do projeto gerando um arquivo de saida ./a.out"
	@echo "    "


compile:
	g++ *.cpp
.PHONY: compile

run: compile
	./a.out
.PHONY: compile